### ISSUE TITLE
SqliteError errors preventing load

### ISSUE THREAD

**Issue by scott-vector** [dunky11/voicesmith#7]
I am receiving the following errors when attempting to run the app:

⠹ Compiling Renderer Code(node:35366) UnhandledPromiseRejectionWarning: SqliteError: no such column: was_aligned
   at Database.prepare (/home/waldo/voicesmith/.webpack/main/index.js:652:21)
    at createTables (/home/waldo/voicesmith/.webpack/main/index.js:7648:8)
    at Object.getInstance (/home/waldo/voicesmith/.webpack/main/index.js:7678:17)
    at Object.getPath (/home/waldo/voicesmith/.webpack/main/index.js:8177:42)
    at /home/waldo/voicesmith/.webpack/main/index.js:8196:52
    at /home/waldo/voicesmith/.webpack/main/index.js:5378:40
    at step (/home/waldo/voicesmith/.webpack/main/index.js:5302:23)
    at Object.next (/home/waldo/voicesmith/.webpack/main/index.js:5283:53)
    at /home/waldo/voicesmith/.webpack/main/index.js:5277:71
    at new Promise (<anonymous>)

AND

Error occurred in handler for 'fetch-needs-install': SqliteError: no such table: settings
    at Database.prepare (/home/waldo/voicesmith/.webpack/main/index.js:652:21)
    at Object.getPath (/home/waldo/voicesmith/.webpack/main/index.js:8178:22)
    at /home/waldo/voicesmith/.webpack/main/index.js:8196:52
    at /home/waldo/voicesmith/.webpack/main/index.js:6545:93
    at step (/home/waldo/voicesmith/.webpack/main/index.js:6518:23)
    at Object.next (/home/waldo/voicesmith/.webpack/main/index.js:6499:53)
    at /home/waldo/voicesmith/.webpack/main/index.js:6493:71
    at new Promise (<anonymous>)
    at __webpack_modules__../src/electron/handles/install.ts.__awaiter (/home/waldo/voicesmith/.webpack/main/index.js:6489:12)
    at /home/waldo/voicesmith/.webpack/main/index.js:6542:91 {
  code: 'SQLITE_ERROR'

**Comment by dunky11** [comment]
Hi, is that [version 2.0](https://github.com/dunky11/voicesmith/releases) downloaded from the releases page?

**Comment by scott-vector** [comment]
Thank you for the information. I will give this a try. I am just exploring to see how Voice Smith works.

**Comment by scott-vector** [comment]
Unfortunately even after installing docker as suggested and restarting, I can load docker in the CLI, but the Voice Smith app is still giving m the "No installation of Docker" message.

**Comment by snufas** [comment]
@dunky11  same issue here, any other recommendations? would love to try this out...

**Comment by snufas** [comment]
@scott-vector 
did you got it working?

**Comment by Snowad14** [comment]
I quickly looked at the code and saw that it runs the docker info command and sees if there is an error which happens if docker is not configured for non-root users, either you can try to run voice-smith as root with no sandbox but that doesn't seem to work on all distributions, you can then configure to accept non-root commands: https://docs.docker.com/engine/install/linux-postinstall/ @snufas

**Comment by snufas** [comment]
@Snowad14 
I loged in to the provided container an saw no sqlight db for voicesmith user running.
one important thing though is i am running the project on windows. it would be easier if that electron app runs as a website ap.
